# Generated by Django 5.0.6 on 2024-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YieldStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('yield_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('max_temp', models.IntegerField(null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('precipitation', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('station_id', 'year')},
            },
        ),
    ]
